script: bundle exec rspec spec
env:
  matrix:
    - RAILS=5.2.4.6
    - RAILS=6.0.3.7
rvm:
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1
jobs:
  exclude:
    - rvm: 2.4.10
      env: RAILS=6.0.3.7
    - rvm: 3.0.1
      env: RAILS=5.2.4.6
